### ISSUE TITLE
Site only shows the background on safari

### ISSUE THREAD

**Issue by ethteck** [pmret/website#10]

**Comment by bates64** [comment]
I can't reproduce. (Version 16.1 (18614.2.9.1.12))

<img width="1009" alt="Screenshot 2023-03-08 at 18 25 52" src="https://user-images.githubusercontent.com/9429556/223801845-491dbc80-9430-46ce-8643-faca644dabbb.png">

**Comment by EllipticEllipsis** [comment]
Mine's `Version 13.1.2 (13609.3.5.1.5)`

**Comment by ethteck** [comment]
this version of safari is obsolete, and it's not ee's main browser so I'm gonna close this. if it becomes an issue for other users, we can re-open it
