### ISSUE TITLE
Info tab content gets truncated

### ISSUE THREAD

**Issue by emmaffiondavies** [pmret/website#8]
# Overview

When checking-out the project via the website just now, I noticed that the content of the info tab gets truncated by the bottom of the pane, as the pane itself doesn't have scrolling enabled.

# Behaviour

## To reproduce

Visit the website's info tab to observe the issue. You may need to reduce your window size if you have a particularly high-DPI display with low system scaling in order to get this issue to manifest.

## Outcomes

When the content on the info tab extends beyond the bottom of the pane...

**Expected:** ... a _scrollbar_ appears and the _user can scroll_ down to view the rest of the content.

**Actual:** ... the rest of the _content gets cut-off_ by the bottom of the pane, as the _pane isn't scrollable_.

## Environment

**I found this while on my laptop:**

* Dell XPS 17 running Windows 11.
* Display resolution is 3840 x 2400 (16:10 aspect ratio) @ 175% system scaling.
* Browser was Microsoft Edge (v110.0.1587.50).

# Workaround

I found that setting the browser zoom to a level below 100% allowed for more content to be seen.

# Screenshot

![Screenshot of truncation](https://user-images.githubusercontent.com/17612522/220955448-77838862-196a-4158-92e1-b91223c031f2.png)

**Comment by bates64** [comment]
Thanks for the detailed report!

I think this was introduced in https://github.com/pmret/website/commit/be18b9479aa3ab9bcde4fde85b214836d6e78f5a#diff-752aae33033979082689dba3e7f51955013615f0535c21ac94265e067da311edR174; `overflow: hidden` should only be present during transitions, not after 😓

**Comment by bates64** [comment]
There's some issue deploying so going to leave this open until everything is all fixed on the live site :)

**Comment by bates64** [comment]
Appears to be fixed!
